services:
  - type: web
    name: assistente-niara
    env: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: python klona_agent.py
    envVars:
      - key: MISTRAL_API_KEY
        sync: false
      - key: PORT
        value: 8000
      - key: HOST
        value: 0.0.0.0
      - key: DEBUG
        value: false
      - key: LOG_LEVEL
        value: info
